### ISSUE TITLE
Assertion Error 

### ISSUE THREAD

**Issue by syedjafer** [githubharald/SimpleHTR#10]
Traceback (most recent call last):
  File "main.py", line 139, in <module>
    main()
  File "main.py", line 115, in main
    loader = DataLoader(FilePaths.fnTrain, Model.batchSize, Model.imgSize, Model.maxTextLen)
  File "/home/syedjafer/Documents/FinalYearProj/SimpleHTR/src/DataLoader.py", line 43, in __init__
    assert (len(lineSplit) >= 9) , "Working" 
AssertionError: Working

**Comment by githubharald** [comment]
there is something wrong with your words.txt file.
Please look at the README, sections "Train model" and "FAQ", to see instructions on how to download the correct words.txt file.

**Comment by syedjafer** [comment]
yeah , i resolved it . Thanks

**Comment by syedjafer** [comment]
How do i train with my own dataset , 
but it resulted in , 
![screenshot from 2018-09-30 21-36-14](https://user-images.githubusercontent.com/20949510/46259594-fcfa5d80-c4f8-11e8-8987-d168f443b1c7.png)

My words .txt 
![screenshot from 2018-09-30 21-37-44](https://user-images.githubusercontent.com/20949510/46259604-3337dd00-c4f9-11e8-9d3b-d42af252a3bf.png)

My dataset 
![screenshot from 2018-09-30 21-38-21](https://user-images.githubusercontent.com/20949510/46259608-3fbc3580-c4f9-11e8-96db-29f918ff19ed.png)

**Comment by githubharald** [comment]
your words.txt is wrong. It should throw an assertion - did you remove it?
Please read the README - I didn't just write it for fun. There you can find a link where a description can be found on how to create words.txt.

**Comment by syedjafer** [comment]
what does getNext function do , 
how to input my input images , 
![screenshot from 2018-09-30 22-07-56](https://user-images.githubusercontent.com/20949510/46259934-6e3c0f80-c4fd-11e8-8108-09bf5b30b6d3.png)

**Comment by githubharald** [comment]
this is up to you. The code is just a skeleton which everyone has to adapt to his or her dataset.
You have to somehow let getNext() return a tuple containing the ground-truth text and image.

**Comment by anidiatm41** [comment]
> yeah , i resolved it . Thanks
@syedjafer @githubharald 
can you please help me , how did you create word.txt file?  I have 4000+ images, their full location and ground truths in an excel . Ground Truths are sentences having max length of 200+.  PLs pls help me how to create words.txt file from them.

PFA a ref image .

![test](https://user-images.githubusercontent.com/52837723/135288901-b6742042-d8b5-47ef-a42e-c8c54d76094d.png)
