### ISSUE TITLE
Same issue as #101 when applying transfer learning

### ISSUE THREAD

**Issue by premtibadiya** [githubharald/SimpleHTR#102]

**Comment by githubharald** [comment]
retrain from scratch. It is really not worth the effort doing any work in this direction for a model that trains in 3h even on a small GPU.

**Comment by premtibadiya** [comment]
I dont have small GPU
But I am trying transfer learning and where is the code which loads the weights trained from IAM dataset

**Comment by githubharald** [comment]
even on CPU is is trained in less than a day. 
If you want to transfer the weights, you have to read the TF documentation how to do this. I simply use the function `tf.train.latest_checkpoint` to load the latest checkpoint file, that means, TF cares about all the details.
