### ISSUE TITLE
Clarification on latest change 

### ISSUE THREAD

**Issue by jjsr** [githubharald/SimpleHTR#108]
Dear Sir, Thanks for appending the line level model, I have the following queries regarding the same-
1) The Model of Thesis is different from the current model?  ( Previously this model is able to work on word level only ) Have you appended it to work for line level by dividing line into words and sending words to recognize ??

2)  Is this  Model.py trainable over line images ??

Note1- Sorry for inconvenience , I am also trying to understand by debugging

**Comment by githubharald** [comment]
> The Model of Thesis is different from the current model? ( Previously this model is able to work on word level only ) Have you appended it to work for line level by dividing line into words and sending words to recognize ??

it's a different model.


> Is this Model.py trainable over line images ??

no, it takes multiple word images, and concatenates them to simulate a text line

**Comment by jjsr** [comment]
Thanks Sir
