### ISSUE TITLE
Does the pretrained model works on French language

### ISSUE THREAD

**Issue by fulsi** [githubharald/SimpleHTR#109]
Hello,

Thank you for this library. 

What will happen if I try to use it with French ? In case of trouble, how could I improve it ? 

Regards,

**Comment by githubharald** [comment]
only works for English characters, so there will be some French characters that are not handled.
See README on how to retrain the model on some other (French) dataset.

**Comment by fulsi** [comment]
Okay, thank you. 

As I understand the character shared between French and English will be recognised but not the specific French character.

Does the beam search looks in a English dictionnary ? In that case, it will broke the french word recognition ?
