### ISSUE TITLE
No learning rate

### ISSUE THREAD

**Issue by rzamarefat** [githubharald/SimpleHTR#110]
Hi sir, could you please explain how can I set a learning rate for this code. I have been scrutinizing the code but was unable to find any parameter for this. If you haven't implemented this how how should I do that. I want this because after some epochs I get 2 - 4 loss for each batch and the overall mean of this is not reduced. I want to set a learning rate scheduler in order to make this more converged. Thank you in advance

**Comment by jjsr** [comment]
HI , there is  a default learning rate for Adam Optimizer see its syntax its 0.01 , if you look into the earlier versions of SimplHtr decaying learning rate was used ( for 1000 epochs its 0.01 and later its 0.001 ) you can manually pass the learning rate parameter as well in the AdamOptimizer . Is this what are you asking ???

**Comment by rzamarefat** [comment]
Thank dear Harald. So sorry for being late in the thread. You helped me a lot.
