### ISSUE TITLE
editdistance

### ISSUE THREAD

**Issue by zico-1** [githubharald/SimpleHTR#112]
Hi after downloading the zip model file. I moved it to the SRC file and ran the main file using pycharm. The issue i have is related to the editdistance module,

1. Tried installing it using pycharm and pip install editdistance, it has refused to install so i came across another one which is edit_distance which i replaced in the code and ran it again. It did work but it does seem like it was not made use of of in the code because i can't find anywhere in the code it was used in the main file.
2. I downloaded the line model but the result i got after running the code was that of the word model.
what would i need to do. Thank you

**Comment by zico-1** [comment]
Alright will try with visual studio. Input image is snapshot 13

**Comment by githubharald** [comment]
image != snapshot

**Comment by jjsr** [comment]
Adding to sir's comment , I have used pycharm to run this repository and have not faced any editdistance issue idea  is you may use Anaconda at the background and try both " pip install editdistance " or " conda install -c conda -forge  editdistance" , pycharm is highly compatible with Anaconda give it a try
