### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by zico-1** [githubharald/SimpleHTR#113]
There are cases where NN have been applied with NLP for handwriting recognition especially in case of recognizing maybe wrongly written word or line say for instance "please" written as "plaese" as this word increase accuracy of recognizing words or lines. Is it that SimpleHTR is only based on NN or it would be too much of processing time and be unnecessary to implement NLP along with NN.

**Comment by githubharald** [comment]
you can use the word beam search decoder (see README on how to use it), which uses a dictionary to correct small mistakes.

**Comment by zico-1** [comment]
and this will also apply to cursive writing style?

**Comment by zico-1** [comment]
Thank you for your response

**Comment by zico-1** [comment]
very much understood. Understood
