### ISSUE TITLE
Model Summary

### ISSUE THREAD

**Issue by rzamarefat** [githubharald/SimpleHTR#117]
Hi, thank you for this awesome implementation. I am trying to convert the model implemented here to the ONNX format. In order to do this I need to know to the name of input layer (CNN) and the output layer in CTC (because ONNX requires these items for the migrated codes from tf1 to tf2). How can I get the summary of the model in order to get these items.

**Comment by githubharald** [comment]
I don't know. Look at the TF documentation.

**Comment by huanghaiyang** [comment]
The name of input is [is_train:0]
The name of output is [save/Const:0]
