### ISSUE TITLE
Same nonsense output for any input when inference

### ISSUE THREAD

**Issue by lamhoangtung** [githubharald/SimpleHTR#12]
- I modified your models with more layers of CNN and MDLSTM instead of Basic LSTM, training and validating worked perfectly for me.
- But when I try to inference a single input images, i get the same output for all input when inference, but  when I feed different image to the infer batch then it will be fine
- Fill all the batch with the same img or with white or black image are all result in same output for any input

Have you ever encountered this weird problem ? What thing that i possibly missed here ? Thanks

**Comment by githubharald** [comment]
a batch has a fixed number of batch elements, therefore I repeat the single image for inference here:
https://github.com/githubharald/SimpleHTR/blob/master/src/main.py#L91
You have to change the code there if you want another behaviour.
