### ISSUE TITLE
Just asking. Is non-english chars allowed?

### ISSUE THREAD

**Issue by muhammedcanpirincci-sudo** [githubharald/SimpleHTR#123]
Can i add my language's char's to charList.txt and train with my language's dataset?
Thanks.

**Comment by githubharald** [comment]
you have to rewrite the data loader for your dataset and then train the model. the chars file is automatically created.
some hints on how to do this see: https://towardsdatascience.com/faq-build-a-handwritten-text-recognition-system-using-tensorflow-27648fb18519

**Comment by githubharald** [comment]
so you basically have to rewrite this class so that it loads your dataset but still has the same interface as it has now:
https://github.com/githubharald/SimpleHTR/blob/master/src/dataloader_iam.py

**Comment by muhammedcanpirincci-sudo** [comment]
so this part. : 1.2 Create IAM-compatible dataset and train model". I saw it but i just wanted to be sure. Thank you so much for your time sir.

**Comment by githubharald** [comment]
yes, either make your dataset look like the IAM dataset and use the original dataloader.
Or write a new dataloader that loads your dataset and make the dataloader look like the original one.

Whatever you prefer.
