### ISSUE TITLE
Readme bad rendering with dark theme

### ISSUE THREAD

**Issue by atsju** [githubharald/SimpleHTR#126]
I suppose this is linked to dark theme but redering is almost not readable.

![image](https://user-images.githubusercontent.com/4628382/148645764-84c42228-c0a8-4675-a36e-23887a70df92.png)

**Comment by githubharald** [comment]
thanks for the hint, never tried it with dark mode, I'll update the png graphics to have white instead of transparent background.

**Comment by githubharald** [comment]
updated. for other repos (e.g. word beam search) I still have to do the changes.
