### ISSUE TITLE
not able to train on different data set using the pretrained model

### ISSUE THREAD

**Issue by ileniTudor** [githubharald/SimpleHTR#132]
Thank you for sharing the work with us. 
I'm trying to generate a new dataset with image size 128x32, but after loading the model 'checkpoints-33', and run self.trainBatch, I have dimensionality issue.

`tensorflow.python.framework.errors_impl.InvalidArgumentError: Conv2DCustomBackpropFilter: filter and out_backprop must have the same out_depth
	 [[node gradients/convolution_grad/Conv2DBackpropFilter (defined at D:\work\ocr-prescription\python\ocrPrescription\SimpleHTR\src\model.py:51) ]]

Errors may have originated from an input operation.
Input Source operations connected to node gradients/convolution_grad/Conv2DBackpropFilter:`

It is about the image dimension size? What is the train dimension size?

**Comment by githubharald** [comment]
Image shape is 128x32 for training in single-word mode, and 256x32 in multi-words mode.
I suggest to check what the shape of the tensor fed to the NN during training looks like.
