### ISSUE TITLE
Training on custom data

### ISSUE THREAD

**Issue by Ateeq1994** [githubharald/SimpleHTR#133]
Hi,
I am using this github link for text recognition. I have performed objection detection on images and got the cropped images. For training on this model it takes img and .txt. I want to know how can I get the .txt format of my data. Thanks.

**Comment by githubharald** [comment]
see [this article](https://towardsdatascience.com/faq-build-a-handwritten-text-recognition-system-using-tensorflow-27648fb18519).

**Comment by Ateeq1994** [comment]
Thank you. I have read it I am trying to convert my data using convertToIAMFormat.py but I am not getting it. Can you please tell where I need to change/edit. Thanks.

**Comment by githubharald** [comment]
sorry, but I don't have the time to give personal guidance.

**Comment by Ateeq1994** [comment]
Sorry for bothering you. Please note that I am stuck at this point in my thesis so kindly help out. Thanks again.

**Comment by Ateeq1994** [comment]
I only have images and no text pairs also.
