### ISSUE TITLE
Handling unicode related issue while working with bentham dataset

### ISSUE THREAD

**Issue by jjsr** [githubharald/SimpleHTR#134]
Dear Sir, Greetings of the day , I am having no issue at all while working with IAM dataset, however if i trying to implement same on bentham dataset , I am stuck while processing the text , Bentham contains total 93 different characters but mine comes out to be 95 having "\xa0" and "©" , should i replace it with blank  "" , or there is a better way to text processing bentham dataset , How you tackled it while working on it . Any suggestion is highly appreciated . Sorry i think this is slightly out of scope of repo . But i would really appreciate your kind help.
` l-1:text = " ".join(open(os.path.join(transactions, x)).read().splitlines())
      l-2: text = html.unescape(text).replace("<gap/>", "")`

{'M', '2', 'H', '©', 'v', 'h', 'c', 'K', 'b', 'j', 'i', '(', ']', 'q', 'f', 'm', 'Q', 's', 't', 'R', '4', '_', '¢', '£', '|', 'E', ';', 'S', ':', 'W', 'e', 'l', '8', 'Ã', '!', '-', '"', ' ', '*', 'J', '5', 'C', 'ª', 'V', 'y', '¥', 'B', '=', 'â', '§', ')', 'r', 'w', 'a', '¨', 'k', 'U', 'x', 'd', 'I', '6', '[', 'D', '?', ',', 'T', 'F', 'A', 'O', '7', '9', 'n', '#', '+', '\xa0', 'g', '3', 'z', 'Â', "'", 'o', 'N', '.', '1', 'Y', 'Š'}

**Comment by githubharald** [comment]
sorry, I don't have the time to provide personal support for custom developments/improvements/....
