### ISSUE TITLE
IAM line dataset input size and maxTextlen parameters values

### ISSUE THREAD

**Issue by Sofiane23i** [githubharald/SimpleHTR#140]
Hello,

Thank you for  sharing your implementation of offline handwriting recognition

To train IAM line dataset, I suppose you modified some parameters like image input size and maxTextLen, (for word dataset it was (128, 32) image input and 32 maxTextlen)

can you share these parameters values please ?

Thanks

**Comment by githubharald** [comment]
in line mode, width is 256 instead of 128, and max. text length is simply width/4.

https://github.com/githubharald/SimpleHTR/blob/master/src/main.py#L26
