### ISSUE TITLE
Multi GPU

### ISSUE THREAD

**Issue by jmyasir** [githubharald/SimpleHTR#144]
Hi, Harald
First of all, thank you for your great work. I've been experimenting a lot with changing the parameters in the model. I want to use my two video cards to be able to do it in less time. But I couldn't do that. I hope you can help.

**Comment by githubharald** [comment]
Running the same training on 2 cards -> not implemented, would require some coding and also I don't think it really helps with such a small model.
What would make more sense is to run 2 trainings at the same time, and have each training on its separate GPU. You could allow passing parameters via command line, this way it would be super-simply to run 2 trainings with different settings at the same time.

**Comment by jmyasir** [comment]
Thank you for your help. I came back late due to vacation.
