### ISSUE TITLE
LSTM layers line context vs word context?

### ISSUE THREAD

**Issue by sophiegonzalez3** [githubharald/SimpleHTR#145]
Hello and thank you for providing all this work 😊

It is a bit of a theoretical question but when it comes to read lines ; from my understanding your model LSTM Layers take the whole line as input (up to 100 char), so they learn the context at the line level without ever learning word concepts. Right ? 

Do you think that using the word model as an input for second LSTM model to reconstruct “meaningful” line from (potentially defective) predicted words would yield better results when train in a specific context (for instance medical journals )?

**Comment by githubharald** [comment]
The only thing that differs between line and word mode is that line mode learns to predict whitespaces between words.
