### ISSUE TITLE
Deployment model as web app

### ISSUE THREAD

**Issue by miracseref** [githubharald/SimpleHTR#147]
Hello Mr. Harald,

First of all, I want to thank you for sharing your work.
I have trouble with the saved model. Since it was trained with TensorFlow 1, the format is slightly different from TensorFlow 2 models. 
I'm building a web app with Flask for deploying this model but I couldn't figure out how to implement the model.
Can you help me?
Thanks

**Comment by githubharald** [comment]
It's trained with TF2, but uses the TF1 operations. So it definitely runs with TF2 (see requirements.txt, there I used tensorflow==2.4.0).

**Comment by miracseref** [comment]
Hello,
Since it uses TF1 operations I'm not able to save the model as a `.h5` or `.pkl` file by doing `model.save() `.
And I don't know how to load TF1 models, so I wonder if you could help to load this model in my Flask web app?
Thanks

**Comment by githubharald** [comment]
You can directly the checkpoint file (as its done [here](https://github.com/githubharald/SimpleHTR/blob/master/src/model.py#L166)), is there a reason why you want to export to h5?

**Comment by miracseref** [comment]
I see, thank you for taking the time. I appreciate it.
The only reason I want to export as an `.h5` is that it's easy to manipulate.
