### ISSUE TITLE
main.py run and says unable to convert function return value to a Python type after reinstallation of Tensorflow and Numpy + upgrades

### ISSUE THREAD

**Issue by eo0017** [githubharald/SimpleHTR#148]
Everytime I run the main.py code, I get this error: 

" File "C:\Users\epoch\anaconda3\envs\spyder-env\lib\site-packages\tensorflow\python\framework\dtypes.py", line 29, in <module>
    _np_bfloat16 = _pywrap_bfloat16.TF_bfloat16_type()

TypeError: Unable to convert function return value to a Python type! The signature was
	() -> handle 
"
I tried solutions both of downgrading and upgrading tensorflow and reinstalling both tensorflow and numpy, and the same issue arose.

**Comment by githubharald** [comment]
Start with an empty venv (or conda env) and then pip install the requirements as described in the README.
