### ISSUE TITLE
I keep getting this error -

### ISSUE THREAD

**Issue by AdarshMJ** [githubharald/SimpleHTR#15]
File "main.py", line 115, in main
    loader = DataLoader(FilePaths.fnTrain, Model.batchSize, Model.imgSize, Model.maxTextLen)
  File "/Users/adarsh/Desktop/SimpleHTR/src/DataLoader.py", line 43, in __init__
    assert len(lineSplit) >= 9
AssertionError

My training file looks like this.

[words.txt](https://github.com/githubharald/SimpleHTR/files/2458741/words.txt)

**Comment by githubharald** [comment]
there is something wrong with the line-breaks which I marked as `[LF]`:
```
a01-000u-00-00 X X X X X X X Any [LF]
[LF]
a01-000u-00-01 X X X X X X X Electrons 
```

There must not be empty lines. Maybe some OS-specific problem (maybe something like: write words.txt e.g. with Linux and read with e.g. Windows).

**Comment by AdarshMJ** [comment]
My os is macOS Mojave. I have removed all the white spaces and the words.txt looks like this 
I still keep getting the same error. Am I missing something?
[words.txt](https://github.com/githubharald/SimpleHTR/files/2460921/words.txt)

**Comment by githubharald** [comment]
there are still line-breaks in your file.

**Comment by AdarshMJ** [comment]
I was able to resolve it thank you!
