### ISSUE TITLE
Blank line filter in dataloader doesn't quite work

### ISSUE THREAD

**Issue by adam-funk** [githubharald/SimpleHTR#151]
I assume line 44 in `dataloader_iam.py` is supposed to ignore blank lines as well as those starting with `#` but it doesn't work because lines read from the open file include the newline at the end. I think `if not line or line[0] == '#'` should be changed to `if not line.strip() or line[0] == '#':`.

**Comment by githubharald** [comment]
I think it was just intended to be used for comment lines, not for empty lines. But ignoring empty lines too makes sense, will add it.
