### ISSUE TITLE
unable to build wheel for word_beam_search

### ISSUE THREAD

**Issue by Simran93504** [githubharald/SimpleHTR#154]
Building wheels for collected packages: word-beam-search
  Building wheel for word-beam-search (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
  note: This error originates from a subprocess, and is likely not a
problem with pip.
  ERROR: Failed building wheel for word-beam-search

**Comment by githubharald** [comment]
this is not enough information to track down the issue. There must be some more information about what exactly fails, and where.
