### ISSUE TITLE
Add feature to save train loss in summary + minor bug fix

### ISSUE THREAD

**Issue by alexeevrevan** [githubharald/SimpleHTR#156]
1) I would like to add the feature that would allow to save the average train loss after every epoch into sгmmary in order to visualise results after the training is done

2) I've also noticed that when results do not improve, the program shows you previous result instead of best one. quite an easy bug to fix, but important

3) Also I would like to write "No improvments for" instead of "No improvments since", because it is more appropriate way to define the distance in English

**Comment by alexeevrevan** [comment]
Hi, Harald, it's me, Alexander, I wrote you an email earlier. Could you assgin this issue to me?

**Comment by githubharald** [comment]
merged.
