### ISSUE TITLE
Should the training text file contain ground truth as well?

### ISSUE THREAD

**Issue by AdarshMJ** [githubharald/SimpleHTR#16]
The words.txt file which is used for training, should it also incorporate a ground truth? Also while training does the main.py make use of the images that were generated as a result of that script used for generating dataset similar to IAM?

I am getting this error 

Ground truth -> Recognized
[ERR:8] "Electric" -> ""
[ERR:8] "Electric" -> ""
[ERR:3] "Any" -> ""
[ERR:9] "Electrons" -> ""
[ERR:9] "Cyclotron" -> ""
[ERR:7] "Induced" -> ""
[ERR:4] "Mass" -> ""
[ERR:4] "Flux" -> ""
[ERR:6] "Region" -> ""
[ERR:1] "p" -> ""
Character error rate: 100.000000%. Word accuracy: 0.000000%.

**Comment by githubharald** [comment]
I don't understand your question.
Please explain in more detail what you mean.

**Comment by AdarshMJ** [comment]
Okay thank you!

I wanted to know, the script which you have provided to generate dataset in the form of IAM Handwriting database, the images generated during this script will have font style defined by this line in the code -  


cv2.putText(img,word,(2,20), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (0), 1, cv2.LINE_AA)
return (word, img)

but this font is not realistic since its not an image of actual handwriting, is it?

Will these images are also used for training along with the words.txt file?
