### ISSUE TITLE
How to convert checkpoint to ONNX

### ISSUE THREAD

**Issue by huanghaiyang** [githubharald/SimpleHTR#163]
Using tensorflow=2.5.0, onnx=1.14.0, tf2onnx=1.14.0/8f8d49

**Comment by huanghaiyang** [comment]
no HTRComponents\scripts\export_crnn_onnx.py

**Comment by githubharald** [comment]
never exported this TF model, so can't help with it.
the onnx model included in the other repo (HTRPipeline) is from another model (for which the training code is not open source).
