### ISSUE TITLE
Outdated version of tensorflow used

### ISSUE THREAD

**Issue by elj40** [githubharald/SimpleHTR#165]
Pip cannot find tensorflow 2.4.0 so throws an error

![image](https://github.com/githubharald/SimpleHTR/assets/66779575/1646e29a-234e-4eb6-837b-de9d62b48a6f)

**Comment by githubharald** [comment]
you can give the closest version a try, 2.5.0, and see if it works.

**Comment by elj40** [comment]
It seems that 2.5.0 will work, but it does throw a lot of warnings that a lot of the functions are deprecated and will be removed soon,.

I still haven't gotten it working but I think its because it says tensorflow 2.5.0 doesnt want to interact nicely with the later versions of tensorflow-intel. I will try again tomorrow in a virtual environment and get back to you.

You can close the issue if you like.

**Comment by elj40** [comment]
Okay I have finally gotten it work!
These were the lowest requirements I found to work:
```
editdistance==0.6.2
patch-ng
lmdb==1.3.0
matplotlib==3.3.0
numpy==1.19.5
opencv-python==4.4.0.46
path==15.0.0
tensorflow==2.5.0
```

I ALSO had to get the Python package for Visual Studio with native packages enabled

**Comment by elj40** [comment]
Maybe just update the requirements so the next person doesn't go through the same pain

**Comment by githubharald** [comment]
thanks a lot for sharing your findings. Next time I do an update I'll push the versions.
For native bindings: this is most likely due to editdistance which gets compiled locally.

**Comment by elj40** [comment]
I forgot to say. Although tensorflow 2.5.0 does work, I still get a lot of warnings of deprecated functions that should be replaced by new ones, so maybe look into those too.

Thanks for making this project. I'm glad it exists
