### ISSUE TITLE
Font style for creating dataset like IAM

### ISSUE THREAD

**Issue by AdarshMJ** [githubharald/SimpleHTR#17]
I wanted to know, the script which you have provided to generate dataset in the form of IAM Handwriting database, the images generated during this script will have font style defined by this line in the code -
cv2.putText(img,word,(2,20), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (0), 1, cv2.LINE_AA)
return (word, img)
but this font is not realistic since its not an image of actual handwriting, is it?

Also while training for new dataset, will the code make use of the image-words.txt pair or just the words.txt?

**Comment by githubharald** [comment]
this is a toy example to create image-text pairs. You, of course, have to adapt the getNext() method to feed your own samples.
