### ISSUE TITLE
Missing CITATION.cff file for repository

### ISSUE THREAD

**Issue by mhucka** [githubharald/SimpleHTR#170]
It would be useful for visitors & researchers if this repository had a [`CITATION.cff`](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) file, so that we can know how to properly cite it. Would you mind adding one, please?

In case it's useful, there is a handy online CITATION.cff file creation tool here: https://citation-file-format.github.io/cff-initializer-javascript/#/

For further motivation: the [Zotero browser plugin](https://www.zotero.org/download/connectors) knows how to read `CITATION.cff` files in GitHub repositories, making it easy for [Zotero](https://www.zotero.org) users to add an entry for the repository to their Zotero bibliography database and thus more likely that they will cite it in their work.

**Comment by githubharald** [comment]
will consider in the future.
