### ISSUE TITLE
where is json

### ISSUE THREAD

**Issue by rengxumiaoshou** [githubharald/SimpleHTR#172]
你好，我想知道JSON文件在哪里，我该如何得到？
I can't find where is the json

`fn_char_list = 'E:\edge下载\SimpleHTR-master\SimpleHTR-master\model\wordCharList.txt'
    **fn_summary = '../model/summary.json'**
    fn_corpus = 'E:\edge下载\SimpleHTR-master\SimpleHTR-master\data\corpus.txt'`

**Comment by githubharald** [comment]
please read the README

**Comment by rengxumiaoshou** [comment]
可能是我之前没有表述清楚

<img width="1280" alt="屏幕截图 2024-03-15 144616" src="https://github.com/githubharald/SimpleHTR/assets/103877103/77b32556-214e-4de8-9984-95cfc0b07e79">
<img width="1280" alt="屏幕截图 2024-03-15 144616" src="https://github.com/githubharald/SimpleHTR/assets/103877103/b56a4d9c-65a8-4955-be18-4802744fddf4">

**Comment by rengxumiaoshou** [comment]
我已经解压并且导入了，但是他仍然提示模组有问题

**Comment by githubharald** [comment]
and most likely, you did not download the model weights

**Comment by rengxumiaoshou** [comment]
Sorry, I naively thought that you also had plug-ins for language translation, and then I would communicate in English. I downloaded and unzipped the word-model and line-model from your readme file as instructed and put it in the model folder as instructed. But the error seems to be saying I didn't save it, you can see the details in the previous image. In my case, I downloaded the pre-trained model from the link provided and placed the unzipped file into the model directory. This process is essentially to get and load the model weights, can you explain it for me, thank you very much. (This is machine translation. Some honorifics I know are not translated. In fact, I respect you very much and hope you could figive me.）

**Comment by githubharald** [comment]
ok, thanks for switching to English, now I get your problem.
I see you unzipped both models to the model/ directory. Please only put one model their, you can choose which one you want to use. So if you want to use the word model, you put all the contents under model/, so that the json and all those files are in model/.

**Comment by rengxumiaoshou** [comment]
thank you very much!!!!

**Comment by rengxumiaoshou** [comment]
Hello, I'm sorry to disturb you again. How to make a front-end webpage for this project, which only needs to be able to open locally. Could you please teach me?
