### ISSUE TITLE
no saved model

### ISSUE THREAD

**Issue by MedhaShankarBhat** [githubharald/SimpleHTR#178]
c:\Users\medha\Downloads\5THSEMMINIPRO\SimpleHTR-master\SimpleHTR-master\src\model.py:73: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  conv_norm = tf.compat.v1.layers.batch_normalization(conv, training=self.is_train)
WARNING:tensorflow:From C:\Users\medha\anaconda3\lib\site-packages\keras\layers\normalization\batch_normalization.py:561: _colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
c:\Users\medha\Downloads\5THSEMMINIPRO\SimpleHTR-master\SimpleHTR-master\src\model.py:86: UserWarning: `tf.nn.rnn_cell.LSTMCell` is deprecated and will be removed in a future version. This class is equivalent as `tf.keras.layers.LSTMCell`, and will be replaced by that in Tensorflow 2.0.
  cells = [tf.compat.v1.nn.rnn_cell.LSTMCell(num_units=num_hidden, state_is_tuple=True) for _ in
WARNING:tensorflow:`tf.nn.rnn_cell.MultiRNNCell` is deprecated. This class is equivalent as `tf.keras.layers.StackedRNNCells`, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From c:\Users\medha\Downloads\5THSEMMINIPRO\SimpleHTR-master\SimpleHTR-master\src\model.py:94: bidirectional_dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.Bidirectional(keras.layers.RNN(cell))`, which is equivalent to this API
WARNING:tensorflow:From C:\Users\medha\anaconda3\lib\site-packages\tensorflow\python\ops\rnn.py:437: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
WARNING:tensorflow:From C:\Users\medha\anaconda3\lib\site-packages\keras\layers\rnn\legacy_cells.py:1048: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Python: 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
Tensorflow: 2.11.0
2024-11-16 15:49:54.316583: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "c:\Users\medha\Downloads\5THSEMMINIPRO\SimpleHTR-master\SimpleHTR-master\src\main.py", line 209, in <module>
    main()
  File "c:\Users\medha\Downloads\5THSEMMINIPRO\SimpleHTR-master\SimpleHTR-master\src\main.py", line 204, in main
    model = Model(char_list_from_file(), decoder_type, must_restore=True, dump=args.dump)
  File "c:\Users\medha\Downloads\5THSEMMINIPRO\SimpleHTR-master\SimpleHTR-master\src\model.py", line 54, in __init__
    self.sess, self.saver = self.setup_tf()
  File "c:\Users\medha\Downloads\5THSEMMINIPRO\SimpleHTR-master\SimpleHTR-master\src\model.py", line 161, in setup_tf
    raise Exception('No saved model found in: ' + model_dir)
Exception: No saved model found in: ../model/.        
I have downloaded the model and added it to model dir in src

**Comment by githubharald** [comment]
you put it in the wrong folder, see README, it is explained there
