### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: Key batch_normalization_1/beta not found in checkpoint

### ISSUE THREAD

**Issue by younestr** [githubharald/SimpleHTR#179]
When running the testing command for this model after training it from scratch , on the words  : "python main.py --img_file ..test_images/word.png" .

I manually inspected the model's snapshot , i found : 
"
"tensor: batch_normalization_1_1/beta (float32) [64]
tensor: batch_normalization_1_1/beta/Adam (float32) [64]
tensor: batch_normalization_1_1/beta/Adam_1 (float32) [64]
tensor: batch_normalization_1_1/gamma (float32) [64]
tensor: batch_normalization_1_1/gamma/Adam (float32) [64]
tensor: batch_normalization_1_1/gamma/Adam_1 (float32) [64]
tensor: batch_normalization_1_1/moving_mean (float32) [64]
tensor: batch_normalization_1_1/moving_variance (float32) [64]
""

P.S : i also did the same with the pretrained model that's provided , but i get the same error

**Comment by githubharald** [comment]
that might be an issue with a wrong TF version. Check if you used the one specified in the requirements.txt file.
