### ISSUE TITLE
How to use sentences for training the model?

### ISSUE THREAD

**Issue by AdarshMJ** [githubharald/SimpleHTR#18]
The corpus.txt file looks like this - 
[corpus.txt](https://github.com/githubharald/SimpleHTR/files/2467736/corpus.txt)

But the corresponding words.txt looks like this 
[words.txt](https://github.com/githubharald/SimpleHTR/files/2467738/words.txt)

The words.txt file in this case has each word of the corpus.txt separately defined, instead of whole sentences, how to achieve this?

**Comment by githubharald** [comment]
this repository implements **word recognition only**. 

Images of sentences are much larger, therefore the neural network size has to be increased. I give some hints how to do this in [this article section 2](https://towardsdatascience.com/27648fb18519), however, I do not provide any code.
