### ISSUE TITLE
Adding new characters

### ISSUE THREAD

**Issue by tony-stark1** [githubharald/SimpleHTR#21]
Hi,

I'm trying to add digit characters to the characters the model can recognize using images from this dataset:
https://www.nist.gov/srd/nist-special-database-19

But when the model finishes training its not able to recognize any digits. I also tried generating images for digits with openCV and adding them to the training, which did improve the performance.
 what would I need to change to achieve this?

**Comment by githubharald** [comment]
I only support the IAM dataset - see issue template.
