### ISSUE TITLE
Instructions for unzipping model.zip

### ISSUE THREAD

**Issue by fireproofsocks** [githubharald/SimpleHTR#22]
This is minor, but it definitely threw some of us for a loop: when unzipping the `model/model.zip`, it's not clear that the contents of that need to be extracted into the `model/` -- on some computers, it ended up extracting to `model/model/` and that doesn't work.  Moving the results of the extraction into the `model/` directory seemed to make things work.

**Comment by githubharald** [comment]
The issue is already discussed in the "FAQ" section, but I think I'll add a short note about it in the "Run demo" section too.

**Comment by fireproofsocks** [comment]
Ah, we did see that down in the FAQ shortly after posting the issue.  It would probably be good to state it redundantly just for fools like us who didn't spot it the first time around.

Also, the `cv2` package is completely weird... one student was able to download it in its python2 version, others could in no wise make the project's requirements fulfilled.  Seems like something is odd about that package that might be worth mentioning in the instructions.  Thanks!
