### ISSUE TITLE
Warning: tensorflow/core/util/ctc/ctc_loss_calculator.cc:144] No valid path found.

### ISSUE THREAD

**Issue by Chazzz** [githubharald/SimpleHTR#28]
p02-109-01-00.png has the label of "----------------------------------------------", which even when truncated to max length of inputs does not result in a findable valid path due to needing additional room for blanks. See https://stackoverflow.com/questions/45130184/ctc-loss-error-no-valid-path-found/45266262#45266262 for further details.

While this doesn't terminate the program, it does result in an infinite gradient for the batch which is possibly detrimental to learning results.

**Comment by githubharald** [comment]
you're absolutely right, repeated chars are encoded by paths containing at least one blank between the repeated chars and therefore reduce the possible text length. I'll have a look at your PR later on.

**Comment by Chazzz** [comment]
Resolved by #29
