### ISSUE TITLE
Issue with featureVals list

### ISSUE THREAD

**Issue by shehryar04** [githubharald/SimpleHTR#3]
https://github.com/githubharald/SimpleHTR/blob/f17540765a6dc589b55a7e693aff424010ce953f/src/Model.py#L42

The featureVals array should be [1, 32, 64, 128, 256] (i.e. one 128 is extra).

**Comment by shehryar04** [comment]
Apologies. I think the code is right as it is.

**Comment by githubharald** [comment]
ok ;-)
