### ISSUE TITLE
Change number of Hidden layers and Neuron in Layers

### ISSUE THREAD

**Issue by shaibiii** [githubharald/SimpleHTR#39]
I am using this code to show behavior of NN in my assignment, I am new to python and unable to understand where number of neurons in each layer and number of hidden layers are specified, and how to change number of hidden layers and number of neurons can be changed ?
1. Versions
Latest TensorFlow version 
Latest Python version
Latest Operating system

**Comment by githubharald** [comment]
See Model.py: variables _kernelVals_ and _featureVals_.
