### ISSUE TITLE
why image is transposed vertically.

### ISSUE THREAD

**Issue by rnirdhar** [githubharald/SimpleHTR#40]
why an image is transposed in pre-processing, what benefit will get from that.
created image like w= 128 and h = 32 but after pre-preprocessing passing to model like h=128 and w=32 why? @githubharald @Chazzz

**Comment by githubharald** [comment]
there's no real reason for this except that in the code where the TF graph is built one works with the "usual" format (w, h) instead of (h, w).

**Comment by rnirdhar** [comment]
thank you, one more question I created new data using cv2,  build a model on that it works fine but when I provide words for testing which is not present in corpus it gives the wrong prediction how to resolve that.
@githubharald

**Comment by Chazzz** [comment]
I'm not githubharald, but it's extremely unfair to Harald for you to ask him for help with **_your code_** without even providing your code and extraordinarily rude to clog his inbox without even taking the effort to utilize proper punctuation and capitalization. So take the time to make your question answerable by a complete stranger doing your work for free, [and also read some advice on how to ask for programming help on the internet](https://codingkilledthecat.wordpress.com/2012/06/26/how-to-ask-for-programming-help/).
