### ISSUE TITLE
Unable to find TFWordBeamSearch.so

### ISSUE THREAD

**Issue by Matt-Payne** [githubharald/SimpleHTR#46]
Given the below error when trying to use --WordBeamSearch. I have gone through the steps to add it and have the TFWordBeamSearch.so in the src folder
* TensorFlow version 1.12
* Python version 3.5
* Operating system Ubuntu 16.04

Traceback (most recent call last):
  File "main.py", line 144, in <module>
    main()
  File "main.py", line 139, in main
    model = Model(open(FilePaths.fnCharList).read(), decoderType, mustRestore=True)
  File "/home/matt/Documents/capstone/ocr/SimpleHTR/src/Model.py", line 39, in __init__
    self.setupCTC()
  File "/home/matt/Documents/capstone/ocr/SimpleHTR/src/Model.py", line 119, in setupCTC
    word_beam_search_module = tf.load_op_library('TFWordBeamSearch.so')
  File "/home/matt/.local/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: TFWordBeamSearch.so: cannot open shared object file: No such file or directory

**Comment by githubharald** [comment]
maybe some issue with the path?
1. Is your working directory the src directory, i.e. did you call the script with python main.py?
2. Try to set the absolute path [here](https://github.com/githubharald/SimpleHTR/blob/master/src/Model.py#L119), i.e. '/home/matt/.../src/TFWordBeamSearch.so' instead of 'TFWordBeamSearch.so'

**Comment by githubharald** [comment]
Closing the issue because of inactivity - if this is still an issue you can reopen it.

**Comment by PartheshSoni** [comment]
Changing the path to  '../src/TFWordBeamSearch.so' worked for me.

**Comment by asadkhilji** [comment]
I have the same issue on Windows 10. I have generated the TFWordBeamSearch.so file but still facing this issue ?
