### ISSUE TITLE
Using model checkpoint for inference.

### ISSUE THREAD

**Issue by ritzyag** [githubharald/SimpleHTR#49]
I have trained a model on my dataset and the model performs decently on validation set. I get an accuracy of 72% using --wordbeamsearch. Now I want to load the model for inference on device. It can be done by converting the model to the .pb format. Now to convert the saved checkpoint to the frozen model I need the name of the output node. I am confused which output node name should I use? Is there a node which can directly give the recognized text (with word beam search decoding) given the input image? Or some other output node name has to be used?

Thank You :)

**Comment by githubharald** [comment]
can't provide any support on this.

**Comment by contactvpatel** [comment]
@githubharald Can you please let us know what is name of Output Node or way to figure out Output Node Name? It's a required parameter to freeze a model to use it in Production.
