### ISSUE TITLE
hand written text

### ISSUE THREAD

**Issue by ssetty** [githubharald/SimpleHTR#5]
Hi,

Thanks for good article.

During training at word level -> CNN learns features of each word.  Then how does decoding happen character by character in each word? I am not clear about what happens at LSTM and CTC layer?

If I give word which is not in IAM dataset (words.tgz) does it work?

Some of handwritten documents have boxes, we fill each character in box - how does this algorithm work?

Thanks

**Comment by githubharald** [comment]
closing this as it is not an issue related to the implementation.
