### ISSUE TITLE
Model Retrained!

### ISSUE THREAD

**Issue by ritzyag** [githubharald/SimpleHTR#52]
Hi!
I have trained a model from scratch. I initially got an accuracy of 42% (word-accuracy) on validation step. I then deleted the checkpoints and retrained the model again but this time I got the validation word-accuracy of 52%. Why is this difference taking place? Is it because of the way test and train data are split? Does training the first time got harder examples to train than the second time?
I had around 1350 data points in total.

I mean how can I assess the performance of my model with such huge difference encountered after every retraining from scratch?

Will this difference become less significant when I have a much bigger dataset?

Thanks a lot in advance!

**Comment by githubharald** [comment]
this is not an issue with the code, therefore closing it.
