### ISSUE TITLE
variable length: resizing vs. padding

### ISSUE THREAD

**Issue by soldierofhell** [githubharald/SimpleHTR#55]
Hi,
Common approach to standarize cropped word images is to resize them to some predefined ratio (height&width). That's fine if the words (=images) are more or less equal length (=have equal ratio). But if length varies we are squeezing and stretching. Probably that's why @githubharald added this kind of augmentation. But I wonder would it be better to rather pad the image with "empty" backgroud to keep the original letter ratio? What do you think folks?

**Comment by githubharald** [comment]
for some information see reference [2] (see README), section 4.2.1.
