### ISSUE TITLE
Output Node Name for Frozen Graph

### ISSUE THREAD

**Issue by contactvpatel** [githubharald/SimpleHTR#56]
- TensorFlow version 1.12
- Python version 3.5
- Operating system - Windows 10

I'm trying to create a frozen graph of a model but the script requires the name of the output node. So I guess this is a request for help and a feature request. Do you know what the output node's name is? I couldn't find it in the code. And as a feature it would be nice to be able to export our model as a frozen inference graph.

**Comment by githubharald** [comment]
Which script do you use? Please share the code.
Output op is the selected CTC decoder, so in this case 'CTCGreedyDecoder':
```
>>> print([x.name for x in tf.get_default_graph().get_operations() if x.name.find('CTC')!=-1])
['CTCLoss', 'CTCLoss_1', 'CTCGreedyDecoder', 'gradients/CTCLoss_grad/PreventGradient', 'gradients/CTCLoss_grad/ExpandDims/dim', 'gradients/CTCLoss_grad/ExpandDims', 'gradients/CTCLoss_grad/mul']
```

The output tensors are then simply the op name + ':x' where x is an integer, e.g. 'CTCGreedyDecoder:0'.

And no, I won't provide a frozen graph nor any feature do achieve this. This is only needed for production which is not the intention of this repository.

**Comment by contactvpatel** [comment]
@githubharald  I am using below article as reference and script to convert SimpleHTR model to .pb file. Please take a look and let me know how to generate .pb file.

https://towardsdatascience.com/deploy-tensorflow-models-9813b5a705d5


import tensorflow as tf
import os

SAVE_PATH = './save'
MODEL_NAME = 'snapshot-5'
VERSION = 1
SERVE_PATH = './serve/{}/{}'.format(MODEL_NAME, VERSION)

checkpoint = tf.train.latest_checkpoint(SAVE_PATH)

tf.reset_default_graph()

with tf.Session() as sess:
    # import the saved graph
    saver = tf.train.import_meta_graph(checkpoint + '.meta')
    # get the graph for this session
    graph = tf.get_default_graph()
    sess.run(tf.global_variables_initializer())
    # get the tensors that we need
    inputs = graph.get_tensor_by_name('inputs:0')
    predictions = graph.get_tensor_by_name('CTCGreedyDecoder:0')
    # create tensors info
    model_input = tf.saved_model.utils.build_tensor_info(inputs)
    model_output = tf.saved_model.utils.build_tensor_info(predictions)
    # build signature definition
    signature_definition = tf.saved_model.signature_def_utils.build_signature_def(
        inputs={'inputs': model_input},
        outputs={'outputs': model_output},
        method_name= tf.saved_model.signature_constants.PREDICT_METHOD_NAME)

    builder = tf.saved_model.builder.SavedModelBuilder(SERVE_PATH)

    builder.add_meta_graph_and_variables(
        sess, [tf.saved_model.tag_constants.SERVING],
        signature_def_map={
            tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY:
                signature_definition
        })
    # Save the model so we can serve it with a model server
    builder.save()

**Comment by contactvpatel** [comment]
@githubharald I am using below article as reference and script to export model. Please take a look and let me know how to export model in .pb file.

https://towardsdatascience.com/deploy-tensorflow-models-9813b5a705d5

`import tensorflow as tf
import os

SAVE_PATH = './save'
MODEL_NAME = 'snapshot-5'
VERSION = 1
SERVE_PATH = './serve/{}/{}'.format(MODEL_NAME, VERSION)

checkpoint = tf.train.latest_checkpoint(SAVE_PATH)

tf.reset_default_graph()

with tf.Session() as sess:
    # import the saved graph
    saver = tf.train.import_meta_graph(checkpoint + '.meta')
    # get the graph for this session
    graph = tf.get_default_graph()
    sess.run(tf.global_variables_initializer())
    # get the tensors that we need
    inputs = graph.get_tensor_by_name('inputs:0')
    predictions = graph.get_tensor_by_name('CTCGreedyDecoder:0')
    # create tensors info
    model_input = tf.saved_model.utils.build_tensor_info(inputs)
    model_output = tf.saved_model.utils.build_tensor_info(predictions)
    # build signature definition
    signature_definition = tf.saved_model.signature_def_utils.build_signature_def(
        inputs={'inputs': model_input},
        outputs={'outputs': model_output},
        method_name= tf.saved_model.signature_constants.PREDICT_METHOD_NAME)

    builder = tf.saved_model.builder.SavedModelBuilder(SERVE_PATH)

    builder.add_meta_graph_and_variables(
        sess, [tf.saved_model.tag_constants.SERVING],
        signature_def_map={
            tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY:
                signature_definition
        })
    # Save the model so we can serve it with a model server :)
    builder.save()

`
