### ISSUE TITLE
Freeze a model 

### ISSUE THREAD

**Issue by phamthuha0970** [githubharald/SimpleHTR#59]
1. Versions
* TensorFlow version 1.12.0
* Python version 3.6.5
* Operating system win10 no cpu

2. Issue
How to freeze a model into pb, but I don't know which of output_node_names to take ? I encountered some of the following errors:
cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\dnn\src\tensorflow\tf_graph_simplifier.cpp:860: error: (-215:Assertion failed) nodesMapIt != nodesMap.end() in function 'cv::dnn::dnn4_v20190122::sortByExecutionOrder' 
How can I take nodesMap.end() out?

**Comment by githubharald** [comment]
In the answer you can find the node names: https://github.com/githubharald/SimpleHTR/issues/56
I can't provide any further help on this.
