### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../model/accuracy.txt

### ISSUE THREAD

**Issue by hcrrch** [githubharald/SimpleHTR#60]
1. Versions
* TensorFlow 1.13.1
* Python 3.6.8
* Windows 10 Pro

2. Issue
  * Whenever I tried to run main.py I got these errors:
  **Traceback (most recent call last):
  File "D:\username\SimpleHTR-master\src\main.py", line 143, in <module>
    main()
  File "D:\username\SimpleHTR-master\src\main.py", line 137, in main
    print(open(FilePaths.fnAccuracy).read())
FileNotFoundError: [Errno 2] No such file or directory: '../model/accuracy.txt'**
I checked and the path is correct (I already extracted the model zip too and put it in model folder), but somehow I keep getting this error.
 * I tried to run this with jupyter notebook too and I got this error
![InkedScreenshot_2019-04-16 main_LI](https://user-images.githubusercontent.com/49245794/56208261-eb366d00-607a-11e9-8298-b4c7bb25a7cc.jpg)

I'm still learning and not familiar with these things yet. I hope you can help me to resolve one of these problem, please. Thank you.

**Comment by githubharald** [comment]
main.py is not intended to be run from an interactive Python session.
Regarding the file accuracy.txt - you screwed up something. I would clone a fresh copy of the repo and try again directly from the command line (for Windows: cmd.exe).
I'm sure you understand that I can't provide personal help on these basic things, therefore I'm closing this issue.
