### ISSUE TITLE
Why the name of repository is SimpleHTR?

### ISSUE THREAD

**Issue by noorulhasan06** [githubharald/SimpleHTR#61]
Thanks for posting such a great article and giving us a good implementation. I just want to ask that is there any advance HTR method you have developed that has very high accuracy. Because as far as know the model (cnn + rnn + ctc) gives 93.2% character accuracy and 79.8% word accuracy.
See this pdf [http://bmvc2018.org/contents/papers/0606.pdf] on table 4.
I am unable to get that result but I will be very thank full to you if you can give me some idea about how to implement and get that results.

**Comment by githubharald** [comment]
because it is a stripped-down version of the model I implemented for my diploma thesis (which is linked in the README).
