### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by JonhSilver** [githubharald/SimpleHTR#62]
c:\Python37>python.exe hwr/train.py
WARNING:tensorflow:From c:\Python37\lib\site-packages\tensorflow\python\framewor
k\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is
 deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-su
nset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From c:\Python37\hwr\rnn.py:73: LSTMCell.__init__ (from tenso
rflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future ve
rsion.
Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by th
at in Tensorflow 2.0.
WARNING:tensorflow:From c:\Python37\hwr\rnn.py:74: MultiRNNCell.__init__ (from t
ensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a futur
e version.
Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replace
d by that in Tensorflow 2.0.
WARNING:tensorflow:From c:\Python37\hwr\rnn.py:81: bidirectional_dynamic_rnn (fr
om tensorflow.python.ops.rnn) is deprecated and will be removed in a future vers
ion.
Instructions for updating:
Please use `keras.layers.Bidirectional(keras.layers.RNN(cell))`, which is equiva
lent to this API
WARNING:tensorflow:From c:\Python37\lib\site-packages\tensorflow\python\ops\rnn.
py:443: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be r
emoved in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
WARNING:tensorflow:From c:\Python37\lib\site-packages\tensorflow\python\ops\rnn.
py:626: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be
 removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From hwr/train.py:72: to_float (from tensorflow.python.ops.ma
th_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Reading ./samples/Images//000033/READ17.000033_01_01_pg_line_1486644351571_780.p

**Comment by githubharald** [comment]
It is developed for TF 1.3 - I don't provide any update for other TF versions.
