### ISSUE TITLE
IAM's form dataset

### ISSUE THREAD

**Issue by Crystaldias** [githubharald/SimpleHTR#64]
I was using this code for IAM's forms dataset. And I received this error. I downloaded the forms.txt file and changed file/dir name in DataLoader.py . But I got this error.
![Capture](https://user-images.githubusercontent.com/38811836/58288106-4709b980-7dd0-11e9-8ded-f32d819c1567.JPG)

**Comment by githubharald** [comment]
you are using the wrong IAM dataset. You must use the words dataset instead.

**Comment by Crystaldias** [comment]
Yes, i used the forms dataset as I have to extract the contents of a form.
