### ISSUE TITLE
Dataloader Module error

### ISSUE THREAD

**Issue by supersaiyan12** [githubharald/SimpleHTR#7]
Hi ,

I'm new in python,facing an issue while importing the dataloder module in jupyter notebook

`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-62-3adc5400ab5d> in <module>()
      3 import cv2
      4 import editdistance
**----> 5 from DataLoader import DataLoader, Batch**
        global DataLoader = undefined
        global Batch = undefined
      6 from Model import Model, DecoderType
      7 from SamplePreprocessor import preprocess

**ModuleNotFoundError: No module named 'DataLoader'`**

**Comment by githubharald** [comment]
Hi,

as I'm not using jupyter I can't give any advice on how to fix it, sorry.
Maybe you have to tell jupyter the paths where the other python files (DataLoader, Model, ...) can be found - but this is just a guess.
Does it work when executing it with the normal python interpreter (`python main.py`)?

**Comment by supersaiyan12** [comment]
Actually i'm only working on jupyter notebook !
i have tried many ways like to download wheel and then install it but it wasn't working either! :(

**Comment by githubharald** [comment]
I'm afraid that I can't help you in this case as I'm not using jupyter.

**Comment by sujitrp** [comment]
Hi I am using windows I am getting similar error 

```
C:\Users\spp07561\Downloads\SimpleHTR\SimpleHTR-master\src>python main.py
Traceback (most recent call last):
  File "C:\Users\spp07561\Downloads\SimpleHTR\SimpleHTR-master\src\main.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

C:\Users\spp07561\Downloads\SimpleHTR\SimpleHTR-master\src>python main.py
Traceback (most recent call last):
  File "C:\Users\spp07561\Downloads\SimpleHTR\SimpleHTR-master\src\main.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

C:\Users\spp07561\Downloads\SimpleHTR\SimpleHTR-master\src>
```
