### ISSUE TITLE
Train model for Hindi language (devanagari script)

### ISSUE THREAD

**Issue by PartheshSoni** [githubharald/SimpleHTR#70]
Hello, you did good work for making this model. I wanted to know how to train your network for language which is not English, like Hindi (Devanagari script). Is the process like the normal one for English or do I need to make changes in the model?

**Comment by githubharald** [comment]
should not be a problem, even though I never tried it.

**Comment by PartheshSoni** [comment]
Sir, 
As you suggested, I have trained the network on Hindi dataset for about 12 hours. Even though Hindi is a more complex language then English, I got an accuracy of 66-67%. What should I do now to improve the accuracy? Should I train it more? Will increasing the number of CNN or RNN layers make any significant improvement in the accuracy? This was just to take your opinion before investing my time in it. I am attaching some images of Hindi  words for your reference (To get an idea about the featural complexity of the language.) 

Thanks for reading.

![36](https://user-images.githubusercontent.com/24564303/60767165-57040100-a0d1-11e9-94b0-813ff0eac14d.jpg)
![35](https://user-images.githubusercontent.com/24564303/60767166-57040100-a0d1-11e9-98df-07413a2ff039.jpg)
![31](https://user-images.githubusercontent.com/24564303/60767167-579c9780-a0d1-11e9-9019-53310be2d2c7.jpg)
![26](https://user-images.githubusercontent.com/24564303/60767168-579c9780-a0d1-11e9-9dd4-670a9c83357c.jpg)

**Comment by githubharald** [comment]
Hi,

thanks for sharing your results :+1: 

The SimpleHTR model is a very small neural network, it is easy to increase the accuracy by just making it larger. To get some ideas, you can have a look at the model I used in my thesis ([link](https://repositum.tuwien.ac.at/obvutwhs/download/pdf/2874742), see section 3.4).
Especially some more CNN layers (e.g. >=7 in total) and changing to 2D LSTM increased the accuracy for me.

Best,
Harald

**Comment by PartheshSoni** [comment]
Ok, I'll check that out. Thanks a lot for your quick reply!
