### ISSUE TITLE
Retraining starts from Epoch 1 always

### ISSUE THREAD

**Issue by Michael-Stanz** [githubharald/SimpleHTR#75]
I looked at main.py and whenever we train using argument --train, it calls the train function
```
def train(model, loader):
	"train NN"
	epoch = 0 # number of training epochs since start
	bestCharErrorRate = float('inf') # best valdiation character error rate
	noImprovementSince = 0 # number of epochs no improvement of character error rate occured
	earlyStopping = 5 # stop training after this 
```
This initialises the bestCharErrorRate to infinity, and epoch to zero
So even if we restore the existing model, the training begins from start

```
# validate
		charErrorRate = validate(model, loader)
		
		# if best validation accuracy so far, save model parameters
		if charErrorRate < bestCharErrorRate:
			print('Character error rate improved, save model')
			bestCharErrorRate = charErrorRate
```
So how to retrain the existing model without starting from scratch so that it starts from the epoch it was ended previously??

**Comment by moto8xpk** [comment]
yeah, I have the same question with @Michael-Stanz  ?

**Comment by githubharald** [comment]
the re-starting is only implemented in a very basic way: the weights are loaded from the pre-trained model.
If you want to implement re-starting, you would need to save the complete state of the training (variables epoch, bestCharErrorRate, ...) and load it when re-starting.

**Comment by Tejas111** [comment]
Thanks for the reply.I will try to hardcode these values for time being.

**Comment by githubharald** [comment]
ok. I'll close the issue for now - if needed just reopen.
