### ISSUE TITLE
Word Segmentation

### ISSUE THREAD

**Issue by kevinkmldn** [githubharald/SimpleHTR#78]
Does in preprocess def, using a word segmentation as you mention on medium? and what is the purpose of the preprocess if it isnt include word segmentation? thanks in advance!

**Comment by githubharald** [comment]
data augmentation + pre-processing for TensorFlow.
For more details, have a look at the code - it is documented.

**Comment by kevinkmldn** [comment]
My bad, i already set dataAugmentation to True , but my image wasnt get augmented properly.
![image](https://user-images.githubusercontent.com/13832489/62609627-54910300-b92c-11e9-9e57-20091ad844ca.png)

The real picture is look like this : 
![aja](https://user-images.githubusercontent.com/13832489/62609697-6e324a80-b92c-11e9-990d-f141305cb4ac.png)

Thank you !
