### ISSUE TITLE
Word Segmentation not working

### ISSUE THREAD

**Issue by kevinkmldn** [githubharald/SimpleHTR#79]
i already set dataAugmentation to True , but my image wasnt get augmented properly.

![image](https://user-images.githubusercontent.com/13832489/62609627-54910300-b92c-11e9-9e57-20091ad844ca.png)

The real picture is look like this : 
![aja](https://user-images.githubusercontent.com/13832489/62609697-6e324a80-b92c-11e9-990d-f141305cb4ac.png)

Thank you !

**Comment by githubharald** [comment]
issue template not filled out, therefore closing it.
ask yourself - how should someone else know what you want by just reading this one line of text?
