### ISSUE TITLE
Text Segmentation

### ISSUE THREAD

**Issue by kevinkmldn** [githubharald/SimpleHTR#80]
1. Versions
* TensorFlow version : 1.13.1
* Python version : 3.6
* Operating system : Windows

2. Issue
* Which result / error did you get?
My result is my image didnt get augmented properly, i already set dataAugmentation on preprocess and infer parameter to True 

`def preprocess(img, imgSize, dataAugmentation=True):
    if img is None:
        img = np.zeros([imgSize[1], imgSize[0]])
    if dataAugmentation:
        stretch = (random.random() - 0.5) # -0.5 .. +0.5
        wStretched = max(int(img.shape[1] * (1 + stretch)), 1) # random width, but at least 1
        img = cv2.resize(img, (wStretched, img.shape[0])) # stretch horizontally by factor 0.5 .. 1.5`

* If you think the result is wrong - what result did you expect instead?
I expect my input image would be augmented and be like IAM Dataset for recognition

![test0](https://user-images.githubusercontent.com/13832489/62670193-8baef500-b9bc-11e9-8b54-05373b844736.png)

* How to reproduce the issue?
I dont know where im wrong,  the code is working fine but the image didnt get augmented

*Provide All Datas
My input image is like this

![aja](https://user-images.githubusercontent.com/13832489/62609697-6e324a80-b92c-11e9-990d-f141305cb4ac.png)

Sorry for my previous post didnt fill the issues template, Thank you so much!

**Comment by githubharald** [comment]
Hi,

the word will NOT be segmented by SimpleHTR. Data augmentation is something different. 
If you want to crop out the text boxes, you could use some text detector first and then apply SimpleHTR for reading.

**Comment by kevinkmldn** [comment]
Thank you for your explanation @githubharald ! can you tell me what is the uses of Data augmentation in the code? and is your WordSegmentation do that or do you have any other references? thanks in advance.

**Comment by githubharald** [comment]
for word segmentation / text detection, you could try [EAST](https://github.com/argman/EAST). But you most likely will have to train it on your data.
There is no out-of-the-box solution I'm aware of.
