### ISSUE TITLE
Visualize Training

### ISSUE THREAD

**Issue by kevinkmldn** [githubharald/SimpleHTR#81]
Hi Harald! Im wondering how to visualize the training or epoch proggress? is it possible? thanks in advance !

**Comment by githubharald** [comment]
I haven't implemented any visualization for SimpleHTR.
You can have a look at TensorBoard, it should be quite simple to implement the visualization of the loss curve.

**Comment by kevinkmldn** [comment]
Thanks for your explaination. But, i want to ask another question. In SimpleHTR, you are using 95% training and 5% validation right? where did the test set? thanks in advance!

**Comment by githubharald** [comment]
I just did a split for training and validation in this case.
You can simply split 90%-5%-5% for training+validation+test.

**Comment by kevinkmldn** [comment]
How do i implement the test data after i split it ? thanks! @githubharald
