### ISSUE TITLE
Loss does not decrease

### ISSUE THREAD

**Issue by hamzarawal** [githubharald/SimpleHTR#92]
Hi, thanks for the awesome work. I am training the model on IAM dataset with everything kept default. But the loss keeps fluctuating between 13 to 15... any idea what can be the reason?

**Comment by githubharald** [comment]
Hi, before digging deeper - can you check if the images are loaded?
We reach this if-block if the image could not be loaded. Can you add a print('IMG NOT LOADED') and run the training again and see if you see the error message printed?
https://github.com/githubharald/SimpleHTR/blob/master/src/SamplePreprocessor.py#L12

**Comment by hamzarawal** [comment]
Hi, thanks for the prompt response. My bad, the images were not loading. The loading directory was not correct.
