### ISSUE TITLE
Word Beam Search Decoder

### ISSUE THREAD

**Issue by shri1107** [githubharald/SimpleHTR#93]
Is it possible to upload the TFWordBeamSearch.so file in this repository or in CTCWordBeamSearch repository. In your code build.sh, it is not updated for latest Tensorflow 2.0 versions.

Also, in this project, the Word Beam Search Decoder is using TF custom operation. Can you also add in the code for NumPy operation (Python package). How it can be utilized in this Simple HTR project ? How to convert the tensorflow session output to a numpy array ?

**Comment by githubharald** [comment]
The SimpleHTR uses the Python package. See instructions in README.

**Comment by shri1107** [comment]
Thanks, but in the SimpleHTR model code, to setup CTC, you have the below code to import the compiled WordBeamSearch operation:
        elif self.decoderType == DecoderType.WordBeamSearch:
            # import compiled word beam search operation (see https://github.com/githubharald/CTCWordBeamSearch)
            word_beam_search_module = tf.load_op_library('TFWordBeamSearch.so')

And in the CTCWordBeamSearch code, the build.sh is not updated to use the latest Tensorflow.
