### ISSUE TITLE
Recognize  Arabic Words using SimpleHTR project

### ISSUE THREAD

**Issue by Tailor2019** [githubharald/SimpleHTR#97]
Hello!
@githubharald 
Thanks a lot for your very helpful project!
I  added the arabic alphabets to charList.txt. But when I run the project it return this error 
"""model = Model(open(FilePaths.fnCharList).read(), decoderType, mustRestore=True, dump=args.dump)
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 81: invalid continuation byte """
Can you please give some explanation how can I recognize Arabic Words using this project ?
Thank you so much!

**Comment by githubharald** [comment]
you can't just add new characters to the model by adding it to the text file.
You will have to get some dataset containing arabic characters, and train the model on that dataset to learn characters.
The error you see is caused by some encoding error, please see the Python doc to see how to handle unicode and utf8.

**Comment by Tailor2019** [comment]
Thank you so much for your reply!

"add new characters to the model by adding it to the text file."
which file i can add the characters ?

Thank in advance!

**Comment by githubharald** [comment]
the character list is created automatically, depending on which chars are in your dataset.

**Comment by Tailor2019** [comment]
@githubharald 
I need to use the finetuning to train my Arabic database.
Please how can I procced ?
Thanks a lot for your response
