### ISSUE TITLE
Batch size

### ISSUE THREAD

**Issue by Tailor2019** [githubharald/SimpleHTR#99]
Hello!
@githubharald 
In main.py the Batch value=100 by default but I train without changing any variable 
the Batch =1095 
""Epoch: 1 Batch: 174/1095 Loss: 13.035996437072754
Epoch: 1 Batch: 175/1095 Loss: 12.717321395874023
Epoch: 1 Batch: 176/1095 Loss: 12.920287132263184
Epoch: 1 Batch: 177/1095 Loss: 11.725905418395996
Epoch: 1 Batch: 178/1095 Loss: 10.567584037780762
Epoch: 1 Batch: 179/1095 Loss: 10.853200912475586
Epoch: 1 Batch: 180/1095 Loss: 10.717955589294434
Epoch: 1 Batch: 181/1095 Loss: 12.011331558227539
Epoch: 1 Batch: 182/1095 Loss: 12.022170066833496
"""
Where it takes this value?
Thanks a lot for your help

**Comment by githubharald** [comment]
number of images per batch != number of batches per epoch.
